@transactionId=371fce74-9541-4533-86aa-d18f2373cb19

# Get Transactions
GET {{$dotenv URL_API}}/transactions

###

GET {{$dotenv URL_API}}/transactions/{{transactionId}}

###

GET {{$dotenv URL_API}}/transactions/summary

# Post Transaction
POST {{$dotenv URL_API}}/transactions
Content-Type: application/json

{
    "amount": 1000,
    "title": "Test Transaction",
    "type": "credit"
}
